export const UPLOADING_MEDIA = 'UPLOADING_MEDIA';
export const UPLOADING_MEDIA_FAILURE = 'UPLOADING_MEDIA_FAILURE';
export const UPLOADING_MEDIA_SUCCESS = 'UPLOADING_MEDIA_SUCCESS';

export const FETCHING_MEDIA = 'FETCHING_MEDIA';
export const FETCHING_MEDIA_FAILURE = 'FETCHING_MEDIA_FAILURE';
export const FETCHING_MEDIA_SUCCESS = 'FETCHING_MEDIA_SUCCESS';